---
title: "Maryland 2024 Voter Analysis: Data Cleaning"
author: "Josh Stim"
date: "2025-02-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readr)
library(dplyr)
```

## Load Registered Voter Data into R
```{r}
reg_voters <- read_tsv(here('../data/LeagueofWomenVotersofBaltimoreCityLawlerNancyScottMakeda/RegisteredVoterList.txt'))
```

### Remove unnecessary columns
```{r}
reg_voters_subset <- reg_voters %>%
select(-c(VTRID, LASTNAME, FIRSTNAME, MIDDLENAME, SUFFIX, HOUSE_SUFFIX, STREET_PREDIRECTION, STREETNAME, STREETTYPE, 
          STREET_POSTDIRECTION, RESIDENTIALCITY, UNITTYPE, UNITNUMBER, ADDRESS, HOUSE_NUMBER, NON_STD_ADDRESS,
          RESIDENTIALSTATE, MAILINGADDRESS, HOUSE_NUMBER, MAILINGCITY, MAILINGSTATE, MAILINGZIP4, MAILINGZIP5, COUNTRY,
          COUNTY, MUNICIPAL_DISTRICTS, COMMISSIONER_DISTRICTS, SCHOOL_DISTRICTS, STATE_REGISTRATION_DATE,
          COUNTY_REGISTRATION_DATE, ...42))
```

```{r}
colnames(reg_voters_subset)
```

```{r}
reg_voters_subset <- reg_voters_subset %>%
  mutate(YOB = year(as.Date(DOB, format = "%m-%d-%Y")),
         GENDER = factor(GENDER),
         PARTY = factor(PARTY),
         RESIDENTIALZIP5 = factor(RESIDENTIALZIP5),
         RESIDENTIALZIP4 = factor(RESIDENTIALZIP4),
         #STATE_REGISTRATION_DATE = as.Date(STATE_REGISTRATION_DATE, format = "%m-%d-%Y"),
         #COUNTY_REGISTRATION_DATE = as.Date(COUNTY_REGISTRATION_DATE, format = "%m-%d-%Y"),
         STATUS_CODE = factor(STATUS_CODE),
         PRECINCT = factor(PRECINCT),
         SPLIT = factor(SPLIT),
         CONGRESSIONAL_DISTRICTS = factor(CONGRESSIONAL_DISTRICTS),
         LEGISLATIVE_DISTRICTS = factor(LEGISLATIVE_DISTRICTS),
         COUNCILMANIC_DISTRICTS = factor(COUNCILMANIC_DISTRICTS),
         WARD_DISTRICTS = factor(WARD_DISTRICTS)
         ) %>%
  select(-DOB)

summary(reg_voters_subset)
```

```{r}
# write.table(reg_voters_subset, file = "RegisteredVotersList_cleaned_v1.tsv", row.names=FALSE, sep="\t")
```

### Structure variables, Prepare for data visualizations
```{r}
# reg_voters_subset <- read_tsv('RegisteredVotersList_cleaned_v1.tsv')
```
```{r}
reg_voters_cleaned <- reg_voters_subset %>%
  mutate(Age = 2024 - YOB) %>% # Calculate age in 2024
  mutate(Age_Group = case_when(
    Age >= 16 & Age <= 17 ~ "16-17",
    Age >= 18 & Age <= 29 ~ "18-29",
    Age >= 30 & Age <= 49 ~ "30-49",
    Age >= 50 & Age <= 64 ~ "50-64",
    Age >= 65 ~ "65+",
    TRUE ~ "Unknown"
  )) %>%
  select(c(GENDER, Age_Group, PRECINCT,LEGISLATIVE_DISTRICTS, COUNCILMANIC_DISTRICTS))

# Calculate Percentages by Council District
age_by_council <- reg_voters_cleaned %>%
  group_by(COUNCILMANIC_DISTRICTS, Age_Group) %>%
  summarise(Count = n()) %>%
  mutate(Age_Percent = Count / sum(Count) * 100) %>%
  select(COUNCILMANIC_DISTRICTS, Age_Group, Age_Percent)

# Data Visualization
ggplot(age_by_council, aes(x = COUNCILMANIC_DISTRICTS, y = Age_Percent, fill = Age_Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Age Breakdown of People Who Registered \nIn 2024 Baltimore City General Election",
    x = "Councilmanic District",
    y = "% of People Who Registered",
    fill = "Age"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

gender_by_council <- reg_voters_cleaned %>%
  group_by(COUNCILMANIC_DISTRICTS, GENDER) %>%
  summarise(Count = n()) %>%
  mutate(Gender_Percent = Count / sum(Count) * 100) %>%
  select(COUNCILMANIC_DISTRICTS, GENDER, Gender_Percent)

# Data visualization
ggplot(gender_by_council, aes(x = COUNCILMANIC_DISTRICTS, y = Gender_Percent, fill = GENDER)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Gender Breakdown of People Who Registered \nIn 2024 Baltimore City General Election",
    x = "Councilmanic District",
    y = "% of People Who Registered",
    fill = "Gender"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

# Calculate Percentages by Legislative District
age_by_legislative <- reg_voters_cleaned %>%
  group_by(LEGISLATIVE_DISTRICTS, Age_Group) %>%
  summarise(Count = n()) %>%
  mutate(Age_Percent = Count / sum(Count) * 100) %>%
  select(LEGISLATIVE_DISTRICTS, Age_Group, Age_Percent)

ggplot(age_by_legislative, aes(x = LEGISLATIVE_DISTRICTS, y = Age_Percent, fill = Age_Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Age Breakdown of People Who Registered \nIn 2024 Baltimore City General Election",
    x = "Legislative District",
    y = "% of People Who Registered",
    fill = "Age"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

gender_by_legislative <- reg_voters_cleaned %>%
  group_by(LEGISLATIVE_DISTRICTS, GENDER) %>%
  summarise(Count = n()) %>%
  mutate(Gender_Percent = Count / sum(Count) * 100) %>%
  select(LEGISLATIVE_DISTRICTS, GENDER, Gender_Percent)

ggplot(gender_by_legislative, aes(x = LEGISLATIVE_DISTRICTS, y = Gender_Percent, fill = GENDER)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Gender Breakdown of People Who Registered \nIn 2024 Baltimore City General Election",
    x = "Legislative District",
    y = "% of People Who Registered",
    fill = "Gender"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```